---
title:       "Workflow: Code style"
author:      "Max Hachemeister"
date:        last-modified
date-format: iso
format:
  gfm:
    toc:     true
---

# Prerequisites

```{r}
#| label: setup
#| results: false

library(tidyverse)
library(nycflights13)
theme_set(theme_light())
```


### 4.6 Exercises

#### 1. Restyle the following pipelines following the guidelines above.

```{r}
#| eval: false

flights|>filter(dest=="IAH")|>group_by(year,month,day)|>summarize(n=n(),delay=mean(arr_delay,na.rm=TRUE))|>filter(n>10)

flights|>filter(carrier=="UA",dest%in%c("IAH","HOU"),sched_dep_time>0900, sched_arr_time<2000)|>group_by(flight)|>summarize(delay=mean(arr_delay,na.rm=TRUE),cancelled=sum(is.na(arr_delay)),n=n())|>filter(n>10)
```

#### Answers
```{r}
#| label: Part 1
#| eval: false

flights |>
  filter(dest == "IAH") |>
  group_by(year, month, day) |>
  summarize(
    n = n(),
    delay = mean(arr_delay, na.rm = TRUE)
  ) |>
  filter(n > 10)
```

```{r}
#| label: Part 2
#| eval: false

flights |>
  filter(
    carrier == "UA",
    dest %in% c("IAH", "HOU"),
    sched_dep_time > 0900,
    sched_arr_time < 2000
  ) |>
  group_by(flight) |>
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    cancelled = sum(is.na(arr_delay)),
    n = n()
  ) |>
  filter(n > 1)
```

