---
title:       "Workflow: Scripts and projects"
author:      "Max Hachemeister"
date:        last-modified
date-format: iso
format:
  gfm:
    toc:     true
---

# Prerequisites

```{r}
#| label: setup
#| results: false

library(tidyverse)
theme_set(theme_light())
```

## Scripts

 - Are the the next stable unit after writing directly in the R console.
 - You can write and format the code first, and afterwards send it for execution to the R process.
 - Good for troubleshooting and iterative programming.
 - R Studio will also help you with marking possible problems in the sidebar.
 - You can also put sections in the script for overview and navigation.
 - These scripts can be shared and are reproducible in some sense.
   - Also as you save them you can search them later on for functions or other code blocks that might be useful beyond the direct purpose of the script.
   
## Projects

 - Refer to a folder containing scripts, plots, data and other in- or output related to a single project.
 - There is also an `environment`, which is the collection of functions, data and objects related to the current project, or eben globally.
   - It is advised to clear it at the end of each session, so to make sure your scripts do  not rely on some ephemeral objects, but create everything within their own code.
   
## Exercises

### 1. Go to the RStudio Tips Twitter account, <https://twitter.com/rstudiotips> and find one tin that looks interesting. Practice using it!

 - Rainbow parentheses, yeas!
   - <https://posit.co/blog/rstudio-1-4-preview-rainbow-parentheses/>

### 2. What other common mistakes will RStudio diagnostics report? Read <https://posit.co/blog/rstudio-1-4-preview-rainbow-parentheses/> to find out.

 - Check whether all arguments in a function were used.
 - Check for missing arguments and commas.
 - Check correct variable definition and usage.
 - Check adherence to RStudio code style.
 - Spellcheck, nice!
 